<input
    type="text"
    class="form-control"
    name="{{$name}}"
    value="{{$value}}"
    placeholder="{{$placeholder}}"
/>
<input
    type="text"
    class="form-control"
    name="{{$name}}"
    value="{{$value}}"
    placeholder="{{$placeholder}}"
/>
